version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
    
sphinx:
  fail_on_warning: true
  

# Declare the Python requirements required to build your docs
python:
   install:
   - requirements: requirements_dev.txt

  
#python:
#  # Install our python package before building the docs
#  install:
#    - method: pip
#      path: .
#      
#      

formats:
  - pdf
  - epub


