version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
    
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true
  

# Declare the Python requirements required to build your docs
python:
   install:
   - requirements: requirements_dev.txt
   - method: pip
     path: .
     

formats:
  - pdf
  - epub


